### ISSUE TITLE
Comma is generated after the last key-value pair in the dictionary (defined in the schema)

### ISSUE THREAD

**Issue by remixer-dec** [noamgat/lm-format-enforcer#17]
Sometimes after generating all the keys in the schema, a wild comma appears and breaks the parser! 

Logs:
```
Terminating the parser. Please open an issue at 
https://github.com/noamgat/lm-format-enforcer/issues with the prefix and CharacterLevelParser parameters
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/lmformatenforcer/tokenenforcer.py", line 78, in _compute_allowed_tokens
    self._collect_allowed_tokens(state.parser, self.tokenizer_tree.root, allowed_tokens, shortcut_key)
  File "/opt/homebrew/lib/python3.10/site-packages/lmformatenforcer/tokenenforcer.py", line 119, in _collect_allowed_tokens
    self._collect_allowed_tokens(next_parser, next_tree_node, allowed_tokens, None)
  File "/opt/homebrew/lib/python3.10/site-packages/lmformatenforcer/tokenenforcer.py", line 117, in _collect_allowed_tokens
    next_parser = parser.add_character(character )
  File "/opt/homebrew/lib/python3.10/site-packages/lmformatenforcer/jsonschemaparser.py", line 56, in add_character
    updated_parser.object_stack[receiving_idx] = updated_parser.object_stack[receiving_idx].add_character(new_character)
  File "/opt/homebrew/lib/python3.10/site-packages/lmformatenforcer/jsonschemaparser.py", line 247, in add_character
    value_schema = self.schema_object.properties[self.current_key]
KeyError: ''
```

Generation examples:
```json
 {
  "key": "val",
  "last_key": [
    {
      "first_inner_key": "value",
      "last_inner_key": ["another_value"]
    }
  ],
```

```json
 {
  "key": "val",
  "last_key": [
    {
      "first_inner_key": "value",
      "last_inner_key": ["another_value"],
      "
```

**Comment by noamgat** [comment]
Thanks! Can you also write the schema you use?

**Comment by remixer-dec** [comment]
In the actual code the schema was generated on the fly from the output of another function, so I don't have it, but here is an abstract example that should match my other examples

```python
from typing import List

class SomeInnerSchema(BaseModel):
  first_inner_key: str
  last_inner_key: List[str]

class SomeSchema(BaseModel)
  key: str
  last_key: List[SomeInnerSchema]


```

basically here both `SomeSchema` and `SomeInnerSchema` have 2 keys, but it started generating more
